from bidict import bidict
from models.types import ElementType

DEFAULT_DICT = {
    "usepackage"         : ElementType.PACKAGE,
    "documentclass"      : ElementType.DOCUMENT_CLASS,
    "author"             : ElementType.AUTHOR,
    "section"            : ElementType.SECTION,
    "figure"             : ElementType.FIGURE,
    "table"              : ElementType.TABLE,
    "ref"                : ElementType.REFERENCE,
    "title"              : ElementType.TITLE,
    "abstract"           : ElementType.ABSTRACT,
    "subsection"         : ElementType.SUBSECTION,
    "subsubsection"      : ElementType.SUBSUBSECTION,
    "paragraph"          : ElementType.PARAGRAPH,
    "equation"           : ElementType.EQUATION,
    "math"               : ElementType.MATH,
    "itemize"            : ElementType.ITEMIZE,
    "enumerate"          : ElementType.ENUMERATE,
    "definition"         : ElementType.DEFINITION,
    "theorem"            : ElementType.THEOREM,
    "proof"              : ElementType.PROOF,
    "algorithm"          : ElementType.ALGORITHM,
    "footnote"           : ElementType.FOOTNOTE,
    "cite"               : ElementType.CITATION,
    "href"               : ElementType.HYPERLINK,
    "thebibliography"    : ElementType.BIBLIOGRAPHY,
    "appendix"           : ElementType.APPENDIX,
    "date"               : ElementType.DATE,
    "verbatim"           : ElementType.CODE_BLOCK,
    "include"            : ElementType.INCLUDE,
    "glossary"           : ElementType.GLOSSARY,
    "index"              : ElementType.INDEX,
    "header"             : ElementType.HEADER,
    "footer"             : ElementType.FOOTER,
    "thepage"            : ElementType.PAGE_NUMBER,
    "marginpar"          : ElementType.MARGIN_NOTE,
    "tableofcontents"    : ElementType.TOC,
    "listoffigures"      : ElementType.LIST_OF_FIGURES,
    "listoftables"       : ElementType.LIST_OF_TABLES,
    "newpage"            : ElementType.NEWPAGE,
    "color"              : ElementType.COLOR,
    "boxed"              : ElementType.BOX,
    "multicols"          : ElementType.COLUMN,
}

IEEE_BIDICT = {
    "IEEEPARstart"         : ElementType.COMMAND,
    "IEEEkeywords"         : ElementType.ENVIRONMENT,
    "IEEEproof"            : ElementType.ENVIRONMENT,
    "IEEEQED"              : ElementType.COMMAND,
    "IEEEQEDhere"          : ElementType.COMMAND,
    "IEEEQEDhereeqn"       : ElementType.COMMAND,
    "IEEEQEDoff"           : ElementType.COMMAND,
    "IEEEeqnarray"         : ElementType.ENVIRONMENT,
    "IEEEeqnarray*"        : ElementType.ENVIRONMENT,
    "IEEEitemize"          : ElementType.ENVIRONMENT,
    "IEEEenumerate"        : ElementType.ENVIRONMENT,
    "IEEEdescription"      : ElementType.ENVIRONMENT,
    "IEEEbiography"        : ElementType.ENVIRONMENT,
    "IEEEbiographynophoto" : ElementType.ENVIRONMENT,
    "IEEEmembership"       : ElementType.COMMAND,
    "IEEEauthorblockA"     : ElementType.COMMAND,
    "IEEEauthorblockN"     : ElementType.COMMAND,
    "IEEEauthorrefmark"    : ElementType.COMMAND,
    "IEEEpubid"            : ElementType.COMMAND,
    "IEEEpubidadjcol"      : ElementType.COMMAND,
    "IEEEspecialpapernotice": ElementType.COMMAND,
}

SPRINGER_BIDICT = {
    "spnewtheorem"     : ElementType.COMMAND,
    "spnewtheorem*"    : ElementType.COMMAND,
    "abstract"         : ElementType.ENVIRONMENT,
    "keywords"         : ElementType.ENVIRONMENT,
    "theorem"          : ElementType.ENVIRONMENT,
    "proposition"      : ElementType.ENVIRONMENT,
    "lemma"            : ElementType.ENVIRONMENT,
    "corollary"        : ElementType.ENVIRONMENT,
    "definition"       : ElementType.ENVIRONMENT,
    "proof"            : ElementType.ENVIRONMENT,
    "acknowledgement"  : ElementType.ENVIRONMENT,
    "vec"              : ElementType.COMMAND,
    "titlerunning"     : ElementType.COMMAND,
    "authorrunning"    : ElementType.COMMAND,
    "inst"             : ElementType.COMMAND,
    "thanks"           : ElementType.COMMAND,
    "example"          : ElementType.ENVIRONMENT,
    "remark"           : ElementType.ENVIRONMENT,
    "smartqed"         : ElementType.COMMAND,
    "doi"              : ElementType.COMMAND,
}
